/**
 * Extract help output from @getdesign/cli and write Markdown pages into
 * src/content/docs/reference/cli/. Invoked by `bun run reference:cli`.
 *
 * The CLI today exposes a single `--help` screen. When subcommands ship,
 * extend SUBCOMMANDS below and a page will be generated per entry.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = resolve(HERE, "..");
const REPO_ROOT = resolve(DOCS_ROOT, "..", "..");
const CLI_ENTRY = join(REPO_ROOT, "packages", "cli", "bin", "getdesign.mjs");
const OUT_DIR = join(DOCS_ROOT, "src", "content", "docs", "reference", "cli");

type CliPage = {
  slug: string;
  title: string;
  description: string;
  args: readonly string[];
};

const SUBCOMMANDS: readonly CliPage[] = [
  {
    slug: "index",
    title: "CLI overview",
    description: "Auto-extracted from `@getdesign/cli --help`.",
    args: ["--help"],
  },
];

function stripAnsi(input: string): string {
  // eslint-disable-next-line no-control-regex
  return input.replace(/\u001b\[[0-9;]*m/g, "");
}

function runHelp(args: readonly string[]): string {
  if (!existsSync(CLI_ENTRY)) {
    return `The CLI entry at ${CLI_ENTRY} was not found. This placeholder will be replaced once the CLI ships.`;
  }

  const result = spawnSync("node", [CLI_ENTRY, ...args], {
    encoding: "utf8",
    timeout: 15_000,
  });

  if (result.error) {
    return `Failed to invoke CLI: ${result.error.message}`;
  }

  const combined = `${result.stdout ?? ""}${result.stderr ?? ""}`.trim();
  return combined.length > 0 ? stripAnsi(combined) : "No output captured.";
}

function renderPage(page: CliPage, output: string): string {
  const frontmatter = [
    "---",
    `title: ${JSON.stringify(page.title)}`,
    `description: ${JSON.stringify(page.description)}`,
    "editUrl: false",
    "---",
    "",
    "<!-- AUTO-GENERATED by apps/docs/scripts/generate-cli-reference.ts. Do not edit by hand. -->",
    "",
    `> Extracted from \`@getdesign/cli ${page.args.join(" ")}\`.`,
    "",
    "```text",
    output,
    "```",
    "",
  ];
  return frontmatter.join("\n");
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });

  for (const page of SUBCOMMANDS) {
    const output = runHelp(page.args);
    const file = join(OUT_DIR, `${page.slug}.md`);
    writeFileSync(file, renderPage(page, output), "utf8");
    console.log(`[docs] wrote ${file}`);
  }
}

main();
