// Generated by scripts/generate-voiceover.ts — do not edit by hand.
export const SCENE_AUDIO_FRAMES = [141, 183, 399, 390, 90, 282] as const;
export const SCENE_FROM_FRAMES = [0, 141, 324, 723, 1113, 1203] as const;
export const LAUNCH_VIDEO_TOTAL_FRAMES = 1485 as const;
