import { execFileSync } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { ElevenLabsClient } from "@elevenlabs/elevenlabs-js";

const FPS = 30;

const SEGMENTS: { id: string; text: string }[] = [
  {
    id: "01-logo",
    text: "Get design. On-demand design systems from any public URL.",
  },
  {
    id: "02-what-is-it",
    text: "Open a real browser, read the page's CSS, and ship a production-grade design dot em dee. ",
  },
  {
    id: "03-how-it-works",
    text: "Here's how it works. Point at a site like Stripe or your own app. The agent crawls HTML and stylesheets, grabs a hero screenshot from a sandboxed browser, and streams back a living design spec. ",
  },
  {
    id: "04-deliverables",
    text: "You get everything on the design page: logo through voice, tokens, components, layout, depth, motion, responsive rules, plus a prompt guide—ready for your design system or handoff.",
  },
  {
    id: "05-architecture",
    text: "It runs on the stack you already use",
  },
  {
    id: "06-finale",
    text: "Ship the design system for any URL. Visit get design dot app, or run en pee ex at get design slash CLI with your favorite site.",
  },
];

/** Safety cap per scene (frames); raise if copy is very long. */
const SCENE_MAX_FRAMES = 900;

function requireBin(name: string): void {
  try {
    execFileSync(name, ["-version"], { stdio: "pipe" });
  } catch {
    console.error(
      `Missing ${name} on PATH. Install ffmpeg (includes ffprobe) on your PATH.`,
    );
    process.exit(1);
  }
}

function probeDurationSeconds(path: string): number {
  const out = execFileSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-show_entries",
      "format=duration",
      "-of",
      "default=noprint_wrappers=1:nokey=1",
      path,
    ],
    { encoding: "utf-8" },
  ).trim();
  const n = Number(out);
  if (!Number.isFinite(n)) {
    throw new Error(`ffprobe returned invalid duration for ${path}: ${out}`);
  }
  return n;
}

/** Whole-frame count that fully contains `durationSec` at `fps` (never shorter than audio). */
function durationToFrames(durationSec: number, fps: number): number {
  let frames = Math.max(1, Math.ceil(durationSec * fps - 1e-9));
  while (frames / fps < durationSec - 1e-6) {
    frames += 1;
  }
  return frames;
}

/**
 * Re-encode to MP3 and pad with silence so the file length is exactly `outSec`
 * (snap to whole frames). Does not trim: if decoder reports longer than outSec,
 * ffprobe after write drives the exported frame count.
 */
function encodeAndPadToSeconds(
  inputPath: string,
  outputPath: string,
  outSec: number,
): void {
  execFileSync(
    "ffmpeg",
    [
      "-y",
      "-i",
      inputPath,
      "-af",
      `apad=whole_dur=${outSec}`,
      "-c:a",
      "libmp3lame",
      "-b:a",
      "128k",
      outputPath,
    ],
    { stdio: "inherit" },
  );
}

async function writeGeneratedVoiceover(
  root: string,
  sceneFrames: number[],
): Promise<void> {
  const fromFrames: number[] = [];
  let acc = 0;
  for (let i = 0; i < sceneFrames.length; i++) {
    fromFrames.push(acc);
    acc += sceneFrames[i]!;
  }
  const total = acc;
  const path = join(root, "src", "generated-voiceover.ts");
  await writeFile(
    path,
    `// Generated by scripts/generate-voiceover.ts — do not edit by hand.\n` +
      `export const SCENE_AUDIO_FRAMES = [${sceneFrames.join(", ")}] as const;\n` +
      `export const SCENE_FROM_FRAMES = [${fromFrames.join(", ")}] as const;\n` +
      `export const LAUNCH_VIDEO_TOTAL_FRAMES = ${total} as const;\n`,
  );
  console.log(
    `Wrote ${path} (${sceneFrames.length} scenes, ${total}f total @ ${FPS}fps)`,
  );
}

async function main(): Promise<void> {
  const apiKey = process.env.ELEVENLABS_API_KEY;
  const voiceId = process.env.ELEVENLABS_VOICE_ID;
  if (!apiKey) {
    console.error("Set ELEVENLABS_API_KEY (e.g. in apps/video/.env).");
    process.exit(1);
  }
  if (!voiceId) {
    console.error("Set ELEVENLABS_VOICE_ID (e.g. in apps/video/.env).");
    process.exit(1);
  }

  requireBin("ffmpeg");
  requireBin("ffprobe");

  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const outDir = join(root, "public", "voiceover", "launch");
  await mkdir(outDir, { recursive: true });

  const client = new ElevenLabsClient({ apiKey });
  const tmpBase = await mkdtemp(join(tmpdir(), "getdesign-vo-"));

  const sceneFrames: number[] = [];

  try {
    for (const seg of SEGMENTS) {
      const rawPath = join(tmpBase, `${seg.id}-raw.mp3`);
      const finalPath = join(outDir, `${seg.id}.mp3`);

      const stream = await client.textToSpeech.convert(voiceId, {
        text: seg.text,
        modelId: "eleven_multilingual_v2",
        outputFormat: "mp3_44100_128",
        voiceSettings: {
          stability: 0.5,
          similarityBoost: 0.75,
          style: 0.25,
        },
      });

      const chunks: Uint8Array[] = [];
      for await (const chunk of stream) {
        chunks.push(chunk);
      }
      await writeFile(rawPath, Buffer.concat(chunks));

      const rawDur = probeDurationSeconds(rawPath);
      let frames = durationToFrames(rawDur, FPS);
      if (frames > SCENE_MAX_FRAMES) {
        console.warn(
          `${seg.id}: ${frames}f exceeds SCENE_MAX_FRAMES (${SCENE_MAX_FRAMES}); trimming. Shorten copy or raise cap.`,
        );
        frames = SCENE_MAX_FRAMES;
      }
      const outSec = frames / FPS;
      console.log(
        `${seg.id}: raw ${rawDur.toFixed(3)}s → ${frames}f (${outSec.toFixed(3)}s, pad-only to frame)`,
      );

      encodeAndPadToSeconds(rawPath, finalPath, outSec);

      const finalDur = probeDurationSeconds(finalPath);
      const verified = durationToFrames(finalDur, FPS);
      sceneFrames.push(verified);
    }
  } finally {
    await rm(tmpBase, { recursive: true, force: true });
  }

  await writeGeneratedVoiceover(root, sceneFrames);

  console.log(`Wrote ${SEGMENTS.length} files to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
